### ISSUE TITLE
Doesn't seem to work correctly with version 2.6

### ISSUE THREAD

**Issue by synergie7** [zeffii/GL-fillet#2]
The extension give an error when used with Blender 2.68. 

Error line 642

Attribute Error "Region object has no attribute 'callback_remove'
